from pathlib import Path
path = Path(r'client/src/config/planetLayers.ts')
text = path.read_text(encoding='utf-8')
text = text.replace('\r\n', '\n')

replacements = {
"      {\n        id: 'base',\n        name: 'Blue Marble',\n        description: 'Natural color imagery',\n        supportsTime: true,\n        minZoom: 0,\n        maxZoom: 8,\n        serverType: 'gibs',\n        serverLayer: 'MODIS_Terra_CorrectedReflectance_TrueColor',\n        tileMatrixSet: 'EPSG4326_250m',\n        format: 'jpeg'\n      },\n": "      {\n        id: 'base',\n        name: 'Blue Marble',\n        description: 'Natural color imagery',\n        supportsTime: true,\n        minZoom: 0,\n        maxZoom: 8,\n        category: 'basemap',\n        metadata: {\n          provider: 'NASA GIBS / Earthdata',\n          sourceUrl: 'https://gibs.earthdata.nasa.gov',\n          spatialResolution: '250 m',\n          temporalCoverage: 'Daily',\n          tags: ['visible', 'true-color']\n        },\n        serverType: 'gibs',\n        serverLayer: 'MODIS_Terra_CorrectedReflectance_TrueColor',\n        tileMatrixSet: 'EPSG4326_250m',\n        format: 'jpeg'\n      },\n",

"      {\n        id: 'thermal',\n        name: 'Thermal',\n        description: 'Surface temperature',\n        supportsTime: true,\n        minZoom: 0,\n        maxZoom: 5,\n        serverType: 'gibs',\n        serverLayer: 'AIRS_L3_Surface_Air_Temperature_Daily_Day',\n        tileMatrixSet: 'EPSG4326_2km',\n        format: 'png',\n        defaultTime: '2021-02-01'\n      },\n": "      {\n        id: 'thermal',\n        name: 'Thermal',\n        description: 'Surface temperature anomaly',\n        supportsTime: true,\n        minZoom: 0,\n        maxZoom: 5,\n        category: 'analysis',\n        metadata: {\n          provider: 'NASA GIBS / AIRS',\n          sourceUrl: 'https://gibs.earthdata.nasa.gov',\n          spatialResolution: '2 km',\n          temporalCoverage: 'Daily',\n          tags: ['infrared', 'temperature']\n        },\n        serverType: 'gibs',\n        serverLayer: 'AIRS_L3_Surface_Air_Temperature_Daily_Day',\n        tileMatrixSet: 'EPSG4326_2km',\n        format: 'png',\n        defaultTime: '2021-02-01'\n      },\n",

"      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'Shaded terrain relief',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 11,\n        serverType: 'gibs',\n        serverLayer: 'SRTM_Color_Index',\n        tileMatrixSet: 'EPSG4326_500m',\n        format: 'png'\n      },\n": "      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'Shaded terrain relief',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 11,\n        category: 'terrain',\n        metadata: {\n          provider: 'NASA GIBS / SRTM',\n          sourceUrl: 'https://gibs.earthdata.nasa.gov',\n          spatialResolution: '500 m',\n          tags: ['topography', 'relief']\n        },\n        serverType: 'gibs',\n        serverLayer: 'SRTM_Color_Index',\n        tileMatrixSet: 'EPSG4326_500m',\n        format: 'png'\n      },\n",

"      {\n        id: 'night',\n        name: 'Night Lights',\n        description: 'City lights at night',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 7,\n        serverType: 'gibs',\n        serverLayer: 'VIIRS_CityLights_2012',\n        tileMatrixSet: 'EPSG4326_500m',\n        format: 'jpeg',\n        defaultTime: '2012-01-01'\n      }\n": "      {\n        id: 'night',\n        name: 'Night Lights',\n        description: 'Global night-time lights',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 7,\n        category: 'night',\n        metadata: {\n          provider: 'NASA GIBS / VIIRS',\n          sourceUrl: 'https://gibs.earthdata.nasa.gov',\n          spatialResolution: '500 m',\n          temporalCoverage: '2012 composite',\n          tags: ['night', 'urbanization']\n        },\n        serverType: 'gibs',\n        serverLayer: 'VIIRS_CityLights_2012',\n        tileMatrixSet: 'EPSG4326_500m',\n        format: 'jpeg',\n        defaultTime: '2012-01-01'\n      }\n",
}

for old, new in replacements.items():
    if old not in text:
        raise SystemExit(f'Block not found for replacement:\n{old}')
    text = text.replace(old, new)

# Mars layers
mars_replacements = {
"      {\n        id: 'base',\n        name: 'CTX Mosaic',\n        description: 'Mars surface mosaic',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 9,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_Viking_MDIM21_ClrMosaic_global_232m/ImageServer',\n        format: 'PNG'\n      },\n": "      {\n        id: 'base',\n        name: 'CTX Mosaic',\n        description: 'Mars global visible mosaic',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 9,\n        category: 'basemap',\n        metadata: {\n          provider: 'NASA JPL / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/mars',\n          spatialResolution: '232 m',\n          tags: ['visible', 'mosaic']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_Viking_MDIM21_ClrMosaic_global_232m/ImageServer',\n        format: 'PNG'\n      },\n",
"      {\n        id: 'thermal',\n        name: 'MOLA Colorized',\n        description: 'Altimetry-based shading',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 8,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_MGS_MOLA_Colorized_DEM_Global_463m/ImageServer',\n        format: 'PNG'\n      },\n": "      {\n        id: 'thermal',\n        name: 'MOLA Colorized',\n        description: 'Colorized Mars elevation from MOLA',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 8,\n        category: 'analysis',\n        metadata: {\n          provider: 'NASA GSFC / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/mars',\n          spatialResolution: '463 m',\n          tags: ['altimetry', 'elevation']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_MGS_MOLA_Colorized_DEM_Global_463m/ImageServer',\n        format: 'PNG'\n      },\n",
"      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'Global elevation model',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 9,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/mola128_mola64_merge_90Nto90S_SimpleC_clon0/ImageServer',\n        format: 'PNG32'\n      },\n": "      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'High-resolution MOLA elevation',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 9,\n        category: 'terrain',\n        metadata: {\n          provider: 'NASA GSFC / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/mars',\n          spatialResolution: '128–64 m',\n          tags: ['elevation', 'terrain']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/mola128_mola64_merge_90Nto90S_SimpleC_clon0/ImageServer',\n        format: 'PNG32'\n      },\n",
"      {\n        id: 'night',\n        name: 'Topography',\n        description: 'Alternate shaded relief',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 8,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_MGS_MOLA_Colorized_DEM_Global_463m/ImageServer',\n        format: 'PNG'\n      }\n": "      {\n        id: 'night',\n        name: 'Topography',\n        description: 'Alternate shaded relief',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 8,\n        category: 'terrain',\n        metadata: {\n          provider: 'NASA GSFC / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/mars',\n          spatialResolution: '463 m',\n          tags: ['relief', 'hillshade']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/mars/trekarcgis/rest/services/Mars_MGS_MOLA_Colorized_DEM_Global_463m/ImageServer',\n        format: 'PNG'\n      }\n",
}

for old, new in mars_replacements.items():
    if old not in text:
        raise SystemExit(f'Mars block not found:\n{old}')
    text = text.replace(old, new)

moon_replacements = {
"      {\n        id: 'base',\n        name: 'LROC WAC',\n        description: 'Global lunar imaging',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 10,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/moon/trekarcgis/rest/services/LRO_WAC_Mosaic_Global_303ppd_v02/ImageServer',\n        format: 'PNG'\n      },\n": "      {\n        id: 'base',\n        name: 'LROC WAC',\n        description: 'Global lunar imaging',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 10,\n        category: 'basemap',\n        metadata: {\n          provider: 'NASA LRO / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/moon',\n          spatialResolution: '303 m',\n          tags: ['lunar', 'visible']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/moon/trekarcgis/rest/services/LRO_WAC_Mosaic_Global_303ppd_v02/ImageServer',\n        format: 'PNG'\n      },\n",
"      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'LOLA elevation model',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 10,\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/moon/trekarcgis/rest/services/LRO_LOLA_DEM_Global_256ppd_v06/ImageServer',\n        format: 'PNG32'\n      }\n": "      {\n        id: 'elevation',\n        name: 'Elevation',\n        description: 'LOLA elevation model',\n        supportsTime: false,\n        minZoom: 0,\n        maxZoom: 10,\n        category: 'terrain',\n        metadata: {\n          provider: 'NASA LRO / Solar System Treks',\n          sourceUrl: 'https://trek.nasa.gov/moon',\n          spatialResolution: '256 m',\n          tags: ['elevation', 'terrain']\n        },\n        serverType: 'arcgis-image',\n        serverEndpoint: 'https://trek.nasa.gov/moon/trekarcgis/rest/services/LRO_LOLA_DEM_Global_256ppd_v06/ImageServer',\n        format: 'PNG32'\n      }\n",
}

for old, new in moon_replacements.items():
    if old not in text:
        raise SystemExit(f'Moon block not found:\n{old}')
    text = text.replace(old, new)

path.write_text(text.replace('\n', '\r\n'), encoding='utf-8')
